nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"

node1:
  build: .
  ports:
     - "3000"
  links:
   - db

node2:
  build: .
  ports:
     - "3000"
  links:
   - db

node3:
  build: .
  ports:
     - "3000"
  links:
   - db

db:
  image: mongo
  ports:
   - "27017"

dbimport:
  build: data/.
  links:
   - db
  command: node DataImport.js -f header.csv -e earn_summary.csv -s sanctions.csv -t time.csv -c mongodb://db:27017/Timesheet

