nginx:
    build: .
    dockerfile: Docker-Nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"

node1:
  build: .
  dockerfile: Docker-Node
  ports:
     - "3000"

node2:
  build: .
  dockerfile: Docker-Node
  ports:
     - "3000"

node3:
  build: .
  dockerfile: Docker-Node
  ports:
     - "3000"
