db:
  #build: data/.
  image: mongo
  ports:
   - "27017:27017"
dbimport:
  build: data/.
  links:
   - db
  command: python MongoDBImport.py -s db -d Timesheet -c users -f data.txt
web:
  build: .
  ports:
     - "8080:3000"
  # Docker file for Node.js handles redirection and source folder definition
  links:
   - db
